compilers:
  - name: Visual Studio
    version: 12
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON
  - name: Visual Studio
    version: 12
    architecture: Win64
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON


