results_repository : NREL/EnergyPlusBuildResults
results_path : _posts
results_base_url : https://nrel.github.io/EnergyPlusBuildResults
regression_repository : NREL/EnergyPlusDevSupport
regression_branch : master
regression_baseline_default : develop
regression_baseline_develop : ""
regression_baseline_master : ""
notification_recipients:
  - lgentile
aging_pull_requests_notification: true
aging_pull_requests_numdays: 14



