compilers:
  - name: "gcc"
    version: "7.5"
    build_package_generator:
     - "STGZ"
     - "TGZ"
     - "IFW"
    release_build_cmake_extra_flags: -DENABLE_REGRESSION_TESTING:BOOL=ON -DBUILD_DOCS:BOOL=ON -DDOCUMENTATION_BUILD="BuildWithAll" -DTEX_INTERACTION="nonstopmode"
    cmake_extra_flags: -DLINK_WITH_PYTHON=ON -DBUILD_FORTRAN=ON -DBUILD_PACKAGE:BOOL=ON -DBUILD_TESTING:BOOL=ON -DENABLE_REGRESSION_TESTING:BOOL=ON -DREGRESSION_BASELINE_PATH:PATH=$REGRESSION_BASELINE -DREGRESSION_SCRIPT_PATH:PATH=$REGRESSION_DIR -DREGRESSION_BASELINE_SHA:STRING=$REGRESSION_BASELINE_SHA -DCOMMIT_SHA=$COMMIT_SHA -DENABLE_GTEST_DEBUG_MODE:BOOL=OFF -DBUILD_PERFORMANCE_TESTS:BOOL=ON -DVALGRIND_ANALYZE_PERFORMANCE_TESTS:BOOL=ON
    collect_performance_results: true
    s3_upload_bucket: energyplus

  - name: "gcc"
    version: "7.5"
    build_type: Debug
    build_package_generator: "STGZ"
    cmake_extra_flags: -DLINK_WITH_PYTHON=ON -DBUILD_FORTRAN=ON -DBUILD_TESTING:BOOL=ON -DENABLE_REGRESSION_TESTING:BOOL=OFF -DCOMMIT_SHA=$COMMIT_SHA -DENABLE_COVERAGE:BOOL=ON -DENABLE_GTEST_DEBUG_MODE:BOOL=OFF
    coverage_enabled: true
    coverage_base_dir: src/EnergyPlus
    coverage_pass_limit: 41.0
    coverage_warn_limit: 40.0
    coverage_s3_bucket: energyplus
    build_tag: UnitTestsCoverage
    ctest_filter: -E "integration.*"
    skip_regression: true
    skip_packaging: true

  - name: "gcc"
    version: "7.5"
    build_type: Debug
    build_package_generator: "STGZ"
    cmake_extra_flags: -DLINK_WITH_PYTHON=ON -DBUILD_FORTRAN=ON -DBUILD_TESTING:BOOL=ON -DENABLE_REGRESSION_TESTING:BOOL=OFF -DCOMMIT_SHA=$COMMIT_SHA -DENABLE_COVERAGE:BOOL=ON -DENABLE_GTEST_DEBUG_MODE:BOOL=OFF
    coverage_enabled: true
    coverage_base_dir: src/EnergyPlus
    coverage_pass_limit: 68.0
    coverage_warn_limit: 67.9
    coverage_s3_bucket: energyplus
    build_tag: IntegrationCoverage
    ctest_filter: -R "integration.*"
    skip_regression: true
    skip_packaging: true
