compilers:
  - name: "gcc"
    version: "11.4"
    cmake_extra_flags: -DLINK_WITH_PYTHON:BOOL=ON -DPYTHON_CLI:BOOL=OFF -DPython_REQUIRED_VERSION:STRING=3.12.2 -DPython_ROOT_DIR:PATH=~/.pyenv/versions/3.12.2/ -DBUILD_FORTRAN:BOOL=ON -DBUILD_TESTING:BOOL=ON -DENABLE_GTEST_DEBUG_MODE:BOOL=OFF -DBUILD_PERFORMANCE_TESTS:BOOL=ON -DVALGRIND_ANALYZE_PERFORMANCE_TESTS:BOOL=ON -DENABLE_PCH:BOOL=OFF
    collect_performance_results: true
    skip_regression: true
    s3_upload_bucket: energyplus

  - name: "gcc"
    version: "11.4"
    build_type: RelWithDebInfo
    cmake_extra_flags: -DLINK_WITH_PYTHON:BOOL=ON -DPYTHON_CLI:BOOL=OFF -DPython_REQUIRED_VERSION:STRING=3.12.2 -DPython_ROOT_DIR:PATH=~/.pyenv/versions/3.12.2/ -DBUILD_FORTRAN:BOOL=ON -DBUILD_TESTING:BOOL=ON -DENABLE_REGRESSION_TESTING:BOOL=OFF -DCOMMIT_SHA:STRING=$COMMIT_SHA -DENABLE_COVERAGE:BOOL=ON -DENABLE_GTEST_DEBUG_MODE:BOOL=OFF -DENABLE_PCH:BOOL=OFF
    coverage_enabled: true
    coverage_base_dir: src/EnergyPlus
    coverage_pass_limit: 41.0
    coverage_warn_limit: 40.0
    coverage_s3_bucket: energyplus
    build_tag: UnitTestsCoverage
    ctest_filter: -E "integration.*"
    skip_regression: true
    skip_packaging: true

  - name: "gcc"
    version: "11.4"
    build_type: RelWithDebInfo
    cmake_extra_flags: -DLINK_WITH_PYTHON:BOOL=ON -DPYTHON_CLI:BOOL=OFF -DPython_REQUIRED_VERSION:STRING=3.12.2 -DPython_ROOT_DIR:PATH=~/.pyenv/versions/3.12.2/ -DBUILD_FORTRAN:BOOL=ON -DBUILD_TESTING:BOOL=ON -DENABLE_REGRESSION_TESTING:BOOL=OFF -DCOMMIT_SHA:STRING=$COMMIT_SHA -DENABLE_COVERAGE:BOOL=ON -DENABLE_GTEST_DEBUG_MODE:BOOL=OFF -DENABLE_PCH:BOOL=OFF
    coverage_enabled: true
    coverage_base_dir: src/EnergyPlus
    coverage_pass_limit: 66.0
    coverage_warn_limit: 67.0
    coverage_s3_bucket: energyplus
    build_tag: IntegrationCoverage
    ctest_filter: -R "integration.*"
    skip_regression: true
    skip_packaging: true
