stages:
  - build
  - test
  - package

build:mac:
  stage: build
  tags:
    - mac
  variables:
    CC: /usr/bin/clang
    CXX: /usr/bin/clang++
    CXXFLAGS: -stdlib=libc++
    CMAKE_OSX_ARCHITECTURES: x86_64
    MACOSX_DEPLOYMENT_TARGET: "10.7"
    SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
  script:
    - mkdir build
    - cd build
    - cmake -DBUILD_FORTRAN=ON -DBUILD_PACKAGE=ON -DBUILD_TESTING=ON -DENABLE_GTEST_DEBUG_MODE=OFF -DCPACK_BINARY_PACKAGEMAKER=ON -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TGZ=OFF ..
    - cmake ..
    - make -j8
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/

build:ubuntu:
  stage: build
  tags:
    - clang
    - ubuntu
  variables:
    CC: /usr/bin/clang-5.0
    CXX: /usr/bin/clang++-5.0
  script:
    - mkdir build
    - cd build
    - cmake -DBUILD_FORTRAN=ON -DBUILD_PACKAGE=ON -DBUILD_TESTING=ON -DENABLE_GTEST_DEBUG_MODE=OFF -DCPACK_BINARY_TGZ=OFF -DCPACK_BINARY_TZ=OFF ..
    - cmake ..
    - make -j8
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/

build:windows:
  stage: build
  tags:
    - vs2017
    - windows
  before_script:
    - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  script:
    - mkdir build
    - cd build
    - '"C:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 15 2017 Win64" -DBUILD_FORTRAN=ON -DBUILD_PACKAGE=ON -DBUILD_TESTING=ON -DENABLE_GTEST_DEBUG_MODE=OFF ..'
    - '"C:\Program Files\CMake\bin\cmake.exe" ..'
    - '"C:\Program Files\CMake\bin\cmake.exe" --build . --config Release --target ALL_BUILD'
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/

test:mac:
  stage: test
  tags:
    - mac
  dependencies:
    - build:mac
  script:
    - cd build
    - ctest -j8

test:ubuntu:
  stage: test
  tags:
    - clang
    - ubuntu
  variables:
    CC: /usr/bin/clang-5.0
    CXX: /usr/bin/clang++-5.0
  dependencies:
    - build:ubuntu
  script:
    - cd build
    - ctest -j8

test:windows:
  stage: test
  tags:
    - vs2017
    - windows
  before_script:
    - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  dependencies:
    - build:windows
  script:
    - cd build
    - '"C:\Program Files\CMake\bin\ctest.exe" -C Release -j8'

package:mac:
  stage: package
  tags:
    - mac
  dependencies:
    - build:mac
  variables:
    CC: /usr/bin/clang
    CXX: /usr/bin/clang++
    CXXFLAGS: -std=c++11 -stdlib=libc++
    CMAKE_OSX_ARCHITECTURES: x86_64
    MACOSX_DEPLOYMENT_TARGET: "10.7"
    SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
  script:
    - cd build
    - make package -j8
  artifacts:
    expire_in: 1 week
    paths:
      - build/EnergyPlus-*.dmg

# # Ubuntu 16.04 EnergyPlus packages are currently failing
# package:ubuntu:
#   stage: package
#   tags:
#     - clang
#     - ubuntu
#   dependencies:
#     - build:ubuntu
#   variables:
#     CC: /usr/bin/clang-5.0
#     CXX: /usr/bin/clang++-5.0
#   script:
#     - cd build
#     - make package -j8
#   artifacts:
#     expire_in: 1 week
#     paths:
#       - build/EnergyPlus-*.sh

package:windows:
  stage: package
  tags:
    - vs2017
    - windows
  before_script:
    - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  dependencies:
    - build:windows
  script:
    - cd build
    - '"C:\Program Files\CMake\bin\cmake.exe" --build . --config Release --target PACKAGE'
  artifacts:
    expire_in: 1 week
    paths:
      - build/EnergyPlus-*.exe
