version: 2

sphinx:
  configuration: doc/readthedocs/sphinx/conf.py
  builder: html

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen

python:
  install:
    - requirements: doc/readthedocs/requirements.txt

submodules:
  exclude: all
