set( CPACK_PACKAGE_VENDOR "US Department of Energy" )

set(CPACK_PACKAGE_VERSION_MAJOR "${CMAKE_VERSION_MAJOR}" )
set(CPACK_PACKAGE_VERSION_MINOR "${CMAKE_VERSION_MINOR}" )
set(CPACK_PACKAGE_VERSION_PATCH "${CMAKE_VERSION_PATCH}" ) 
set(PROJECT_VERSION_STRING ${CPACK_PACKAGE_VERSION_MAJOR}-${CPACK_PACKAGE_VERSION_MINOR}-${CPACK_PACKAGE_VERSION_PATCH} )

if( win32 AND NOT unix )
  include(InstallRequiredSystemLibraries)
  if(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS)
    install(FILES ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS} DESTINATION ".")
  endif()
endif()

if( APPLE )
  set(CPACK_PACKAGE_DEFAULT_LOCATION /Applications)
endif()

set(CPACK_PACKAGING_INSTALL_PREFIX "/${CMAKE_PROJECT_NAME}-${PROJECT_VERSION_STRING}")

install_remote(FILES https://raw.githubusercontent.com/NREL/OpenStudio/develop/license.txt ./)

# Install files that are in the current repo
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/AirCooledChiller.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/ASHRAE_2005_HOF_Materials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Boilers.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/California_Title_24-2008.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Chillers.idf" DESTINATION "./DataSets")
#INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Color Choices.dxf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/CompositeWallConstructions.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/DXCoolingCoil.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/ElectricGenerators.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/ElectricityUSAEnvironmentalImpactFactors.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/ElectronicEnthalpyEconomizerCurves.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/ExhaustFiredChiller.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/FluidPropertiesRefData.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/FossilFuelEnvironmentalImpactFactors.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/GLHERefData.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/GlycolPropertiesRefData.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/LCCusePriceEscalationDataSet2010.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/LCCusePriceEscalationDataSet2011.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/LCCusePriceEscalationDataSet2012.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/MoistureMaterials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/PerfCurves.idf" DESTINATION "./DataSets")
#INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/PrecipitationSchedulesUSA-fullset_Release.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/PrecipitationSchedulesUSA.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/RefrigerationCasesDataSet.idf" DESTINATION "./DataSets")
#INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/RefrigerationCases.idf" DESTINATION "./DataSets")
#INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/RefrigerationCasesSetNumberOne.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/RefrigerationCompressorCurves.idf" DESTINATION "./DataSets")
#INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/RefrigerationCompressorCurvesNeedFix.idf" DESTINATION "./DataSets")
#INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/RefrigerationCompressorCurvesOK.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/ResidentialACsAndHPsPerfCurves.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/RooftopPackagedHeatPump.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/SandiaPVdata.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Schedules.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/SolarCollectors.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/StandardReports.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/SurfaceColorSchemes.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/USHolidays-DST.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Window5DataFile.dat" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/WindowBlindMaterials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/WindowConstructs.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/WindowGasMaterials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/WindowGlassMaterials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/WindowScreenMaterials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/WindowShadeMaterials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/FMUs/MoistAir.fmu" DESTINATION "./DataSets/FMUs")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/FMUs/ShadingController.fmu" DESTINATION "./DataSets/FMUs")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/TDV/TDV_2008_kBtu_CTZ06.csv" DESTINATION "./DataSets/TDV")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/TDV/TDV_read_me.txt" DESTINATION "./DataSets/TDV")

# not sure why, but at least on my linux build the macro dataset files weren't in the DataSets folder
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Macro/Locations-DesignDays.xls" DESTINATION "./MacroDataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Macro/SandiaPVdata.imf" DESTINATION "./MacroDataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Macro/SolarCollectors.imf" DESTINATION "./MacroDataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Macro/UtilityTariffObjects.imf" DESTINATION "./MacroDataSets")

# weather files
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_CA_San.Francisco.Intl.AP.724940_TMY3.ddy" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_CA_San.Francisco.Intl.AP.724940_TMY3.stat" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_CO_Golden-NREL.724666_TMY3.ddy" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_CO_Golden-NREL.724666_TMY3.epw" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_CO_Golden-NREL.724666_TMY3.stat" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_FL_Tampa.Intl.AP.722110_TMY3.ddy" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_FL_Tampa.Intl.AP.722110_TMY3.epw" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_FL_Tampa.Intl.AP.722110_TMY3.stat" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.ddy" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.stat" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_VA_Sterling-Washington.Dulles.Intl.AP.724030_TMY3.ddy" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_VA_Sterling-Washington.Dulles.Intl.AP.724030_TMY3.epw" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_VA_Sterling-Washington.Dulles.Intl.AP.724030_TMY3.stat" DESTINATION "./WeatherData")

###########################################
# Now install files that are in other repos
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/Acknowledgments.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/appguidemenu.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/AuxiliaryPrograms.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/devguidemenu.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/EMS_Application_Guide.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/EngineeringReference.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/EPlusMainMenu.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/ExternalInterfaces_Application_Guide.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/GettingStarted.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/index.pdx" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/InputOutputReference.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/InterfaceDeveloper.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/ModuleDeveloper.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/OutputDetailsAndExamples.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/PlantApplicationGuide.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/ProgrammingStandard.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/Tips_and_Tricks_Using_EnergyPlus.pdf" DESTINATION "./Documentation")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/docs/pdf/Using_EnergyPlus_for_Compliance.pdf" DESTINATION "./Documentation")

INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/Addressed_Issues-V8-1-0.html" DESTINATION "./")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/Bugreprt.txt" DESTINATION "./")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/Enhancement_List_Items-V8-1-0.html" DESTINATION "./")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/ep.gif" DESTINATION "./")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/Known_Issues-V8-1-0.html" DESTINATION "./")
#INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/license.txt" DESTINATION "./")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/ObjectStatus.xls" DESTINATION "./")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/readme.html" DESTINATION "./")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/Rules8-0-0-to-8-1-0.xls" DESTINATION "./")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/VariableNameListAudit.xlsx" DESTINATION "./")

INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/ExampleFilesDoc.txt" DESTINATION "./ExampleFiles")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/ExampleFiles-ObjectsLink.xls" DESTINATION "./ExampleFiles")
INSTALL(FILES "${EPLUS_BUILDSUPPORT_REPO}/release/ExampleFiles.xls" DESTINATION "./ExampleFiles")

INCLUDE(CPack)

