name: Flake8

on: [push]

jobs:
  flake8:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Pip Dependencies
      run: pip install flake8

    - name: Run Flake8
      run: flake8 src
