name: Releases

on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            pyinstall_args: ""
          - os: ubuntu-18.04
            pyinstall_args: ""
          - os: macos-10.15
            pyinstall_args: --onefile --windowed
          - os: windows-2019
            pyinstall_args: --windowed

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Pip Dependencies
      shell: bash
      run: pip install pyinstaller

    - name: Build
      shell: bash
      run: pyinstaller ${{ matrix.pyinstall_args }} main.spec

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: EPLaunch-${{ matrix.os }}
        path: dist/main
