name: Windows 64-bit Testing

on: [push]

env:
  CMAKE_Fortran_COMPILER: "/c/msys64/mingw64/bin/x86_64-w64-mingw32-gfortran.exe"

jobs:
  windows_test_64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: 'x64'

    - name: Create Build Directory
      run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      run: cmake -G "Visual Studio 16 2019" -A x64 -DLINK_WITH_PYTHON=ON -DBUILD_TESTING=ON -DBUILD_FORTRAN=ON ..

    - name: Build EnergyPlus
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      shell: bash
      run: cmake --build . -j 2 --config Release

    - name: Run Tests
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      run: ctest -j 2 -C Release
