name: Linux Test - Debug Mode

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    # install boto to upload coverage results

    - name: Install APT dependencies
      # install gcovr and coverage stuff
      run: sudo apt-get update && sudo apt-get install libxkbcommon-x11-0 xorg-dev libgl1-mesa-dev

    - name: Create Build Directory
      run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      # turn on ENABLE_COVERAGE
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DLINK_WITH_PYTHON=ON -DDOCUMENTATION_BUILD="BuildWithAll" -DTEX_INTERACTION="batchmode" -DBUILD_FORTRAN=ON -DBUILD_PACKAGE:BOOL=ON ..

    - name: Build EnergyPlus
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      run: cmake --build . -j 2

    - name: Run EnergyPlus Unit Tests
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      run: ctest -j 2 -E "integration.*"

    # get coverage results here, upload them, then clear them

    - name: Run EnergyPlus Integration Tests
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      run: ctest -j 2 -R "integration.*"

    # get coverage results here, upload them
