configure_file("${IDD_SOURCE_PATH}" "${IDD_OUTPUT_PATH}")
get_filename_component(IDD_HIDDEN_DIRECTORY "${IDD_HIDDEN_OUTPUT_PATH}" DIRECTORY )
get_filename_component(IDD_NAME "${IDD_OUTPUT_PATH}" NAME)
file(COPY "${IDD_OUTPUT_PATH}" DESTINATION "${IDD_HIDDEN_DIRECTORY}")
file(RENAME "${IDD_HIDDEN_DIRECTORY}/${IDD_NAME}" "${IDD_HIDDEN_OUTPUT_PATH}")
file(WRITE "${IDD_STAMP_PATH}")

