set( CPACK_PACKAGE_VENDOR "US Department of Energy" )

list(APPEND CMAKE_MODULE_PATH "${CMAKE_BINARY_DIR}/Modules")

set(CPACK_PACKAGE_VERSION_MAJOR "${CMAKE_VERSION_MAJOR}" )
set(CPACK_PACKAGE_VERSION_MINOR "${CMAKE_VERSION_MINOR}" )
set(CPACK_PACKAGE_VERSION_PATCH "${CMAKE_VERSION_PATCH}" )
set(CPACK_PACKAGE_VERSION_BUILD "${CMAKE_VERSION_BUILD}" )

set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}-${CPACK_PACKAGE_VERSION_BUILD}")

# set the buildsupport reference (branch name/tag)
SET( BUILDSUPPORTREF master )

SET( BUILDSUPPORTDIR ${CMAKE_BINARY_DIR}/BuildSupport )

include(cmake/TargetArch.cmake)
target_architecture(TARGET_ARCH)

if ( "${CMAKE_BUILD_TYPE}" STREQUAL "" OR "${CMAKE_BUILD_TYPE}" STREQUAL "Release" )
  set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_NAME}-${TARGET_ARCH}")
else()
  set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_NAME}-${TARGET_ARCH}-${CMAKE_BUILD_TYPE}")
endif()

set(CPACK_PACKAGING_INSTALL_PREFIX "/${CMAKE_PROJECT_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}-${CPACK_PACKAGE_VERSION_MINOR}-${CPACK_PACKAGE_VERSION_PATCH}")

if( WIN32 AND NOT UNIX )
  set(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP TRUE)
  include(InstallRequiredSystemLibraries)
  if(CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS)
  install(PROGRAMS ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS} DESTINATION "./")
  endif()
endif()

install(FILES "${CMAKE_SOURCE_DIR}/LICENSE.txt" DESTINATION "./")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE.txt")

install( FILES "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Energy+.idd" DESTINATION ./ )

# Some docs are generated on the fly here, create a dir for the 'built' files
set( DOCS_OUT "${CMAKE_BINARY_DIR}/autodocs" )
install(CODE "execute_process(COMMAND \"${CMAKE_COMMAND}\" -E make_directory \"${DOCS_OUT}\")")

# the output variables listing
install(CODE "execute_process(COMMAND \"${PYTHON_EXECUTABLE}\" \"${CMAKE_SOURCE_DIR}/doc/tools/parse_output_variables.py\" \"${CMAKE_SOURCE_DIR}/src/EnergyPlus\" \"${DOCS_OUT}/SetupOutputVariables.csv\" \"${DOCS_OUT}/SetupOutputVariables.md\")")
install(FILES "${CMAKE_BINARY_DIR}/autodocs/SetupOutputVariables.csv" DESTINATION "./")

# the example file summary
install(CODE "execute_process(COMMAND \"${PYTHON_EXECUTABLE}\" \"${CMAKE_SOURCE_DIR}/doc/tools/example_file_summary.py\" \"${CMAKE_SOURCE_DIR}/testfiles\" \"${DOCS_OUT}/ExampleFiles.html\")")
install(FILES "${DOCS_OUT}/ExampleFiles.html" DESTINATION "./ExampleFiles/")

# the example file objects link
install(CODE "execute_process(COMMAND \"${PYTHON_EXECUTABLE}\" \"${CMAKE_SOURCE_DIR}/doc/tools/example_file_objects.py\" \"${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Energy+.idd\" \"${CMAKE_SOURCE_DIR}/testfiles\" \"${DOCS_OUT}/ExampleFiles-ObjectsLink.html\")")
install(FILES "${DOCS_OUT}/ExampleFiles-ObjectsLink.html" DESTINATION "./ExampleFiles/")

# the change log, only if we do have a github token in the environment
# Watch out! GITHUB_TOKEN could go out of scope by the time install target is run.
# Better to move this condition into the install CODE.
if(NOT "$ENV{GITHUB_TOKEN}" STREQUAL "")
	install(CODE "execute_process(COMMAND \"${PYTHON_EXECUTABLE}\" \"${CMAKE_SOURCE_DIR}/doc/tools/create_changelog.py\" \"${CMAKE_SOURCE_DIR}\" \"${DOCS_OUT}/changelog.md\" \"${DOCS_OUT}/changelog.html\" \"${GIT_EXECUTABLE}\" \"$ENV{GITHUB_TOKEN}\" \"${PREV_RELEASE_SHA}\" \"${CPACK_PACKAGE_VERSION}\")")
  install(FILES "${DOCS_OUT}/changelog.html" DESTINATION "./" OPTIONAL)
else()
  message(WARNING "No GITHUB_TOKEN found in environment; package won't be complete")
endif()

# Install files that are in the current repo
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/AirCooledChiller.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/ASHRAE_2005_HOF_Materials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Boilers.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/California_Title_24-2008.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Chillers.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/CompositeWallConstructions.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/DXCoolingCoil.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/ElectricGenerators.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/ElectricityUSAEnvironmentalImpactFactors.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/ElectronicEnthalpyEconomizerCurves.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/ExhaustFiredChiller.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/FluidPropertiesRefData.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/FossilFuelEnvironmentalImpactFactors.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/GLHERefData.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/GlycolPropertiesRefData.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/LCCusePriceEscalationDataSet2011.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/LCCusePriceEscalationDataSet2012.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/LCCusePriceEscalationDataSet2013.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/LCCusePriceEscalationDataSet2014.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/LCCusePriceEscalationDataSet2015.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/MoistureMaterials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/PerfCurves.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/PrecipitationSchedulesUSA.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/RefrigerationCasesDataSet.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/RefrigerationCompressorCurves.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/ResidentialACsAndHPsPerfCurves.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/RooftopPackagedHeatPump.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/SandiaPVdata.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Schedules.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/SolarCollectors.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/StandardReports.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/SurfaceColorSchemes.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/USHolidays-DST.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Window5DataFile.dat" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/WindowBlindMaterials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/WindowConstructs.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/WindowGasMaterials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/WindowGlassMaterials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/WindowScreenMaterials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/WindowShadeMaterials.idf" DESTINATION "./DataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/FMUs/MoistAir.fmu" DESTINATION "./DataSets/FMUs")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/FMUs/ShadingController.fmu" DESTINATION "./DataSets/FMUs")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/TDV/TDV_2008_kBtu_CTZ06.csv" DESTINATION "./DataSets/TDV")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/TDV/TDV_read_me.txt" DESTINATION "./DataSets/TDV")

INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Macro/Locations-DesignDays.xls" DESTINATION "./MacroDataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Macro/SandiaPVdata.imf" DESTINATION "./MacroDataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Macro/SolarCollectors.imf" DESTINATION "./MacroDataSets")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/datasets/Macro/UtilityTariffObjects.imf" DESTINATION "./MacroDataSets")

# weather files
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_CA_San.Francisco.Intl.AP.724940_TMY3.ddy" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_CA_San.Francisco.Intl.AP.724940_TMY3.stat" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_CO_Golden-NREL.724666_TMY3.ddy" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_CO_Golden-NREL.724666_TMY3.epw" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_CO_Golden-NREL.724666_TMY3.stat" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_FL_Tampa.Intl.AP.722110_TMY3.ddy" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_FL_Tampa.Intl.AP.722110_TMY3.epw" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_FL_Tampa.Intl.AP.722110_TMY3.stat" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.ddy" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.stat" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_VA_Sterling-Washington.Dulles.Intl.AP.724030_TMY3.ddy" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_VA_Sterling-Washington.Dulles.Intl.AP.724030_TMY3.epw" DESTINATION "./WeatherData")
INSTALL(FILES "${CMAKE_SOURCE_DIR}/weather/USA_VA_Sterling-Washington.Dulles.Intl.AP.724030_TMY3.stat" DESTINATION "./WeatherData")

INSTALL( DIRECTORY testfiles/ DESTINATION ExampleFiles/
  PATTERN _* EXCLUDE
  PATTERN *.ddy EXCLUDE
  PATTERN CMakeLists.txt EXCLUDE
)

# TODO Remove version from file name or generate
# These files names are stored in variables because they also appear as start menu shortcuts later.
set( RULES_XLS Rules8-4-0-to-8-5-0.xls )
install(FILES "${CMAKE_SOURCE_DIR}/release/Bugreprt.txt" DESTINATION "./")
install(FILES "${CMAKE_SOURCE_DIR}/release/ep.gif" DESTINATION "./")
install(FILES "${CMAKE_SOURCE_DIR}/release/readme.html" DESTINATION "./")
install(FILES "${CMAKE_SOURCE_DIR}/src/Transition/InputRulesFiles/${RULES_XLS}" DESTINATION "./")
install(FILES "${CMAKE_SOURCE_DIR}/src/Transition/OutputRulesFiles/OutputChanges8-4-0-to-8-5-0.md" DESTINATION "./")
install(FILES "${BUILDSUPPORTDIR}/bin/CurveFitTools/IceStorageCurveFitTool.xlsm" DESTINATION "PreProcess/HVACCurveFitTool/")
install(FILES "${CMAKE_SOURCE_DIR}/src/Transition/SupportFiles/Report Variables 8-4-0 to 8-5-0.csv" DESTINATION "PreProcess/IDFVersionUpdater/")
install(FILES "${CMAKE_SOURCE_DIR}/idd/V8-4-0-Energy+.idd" DESTINATION "PreProcess/IDFVersionUpdater/")
install( FILES "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/Energy+.idd" DESTINATION "PreProcess/IDFVersionUpdater/" RENAME "V8-5-0-Energy+.idd" )

if( WIN32 )
  # calcsoilsurftemp is now built from source, just need to install the batch run script
  INSTALL(FILES "${CMAKE_SOURCE_DIR}/src/CalcSoilSurfTemp/RunCalcSoilSurfTemp.bat" DESTINATION "PreProcess/CalcSoilSurfTemp/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/EP-Launch.exe" "./")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/Epl-run.bat" "./")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/RunDirMulti.bat" "./")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/RunEP.ico" "./")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/RunEPlus.bat" "./")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/RunReadESO.bat" "./")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/Runep.pif" "./")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PostProcess/AppGPostProcess/appgpostprocess.exe" "PostProcess/AppGPostProcess/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PostProcess/CSVproc.exe" "PostProcess/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PostProcess/RunReadESO.bat" "PostProcess/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/CoeffConv/CoeffCheck.exe" "PreProcess/CoeffConv/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/CoeffConv/CoeffCheckExample.cci" "PreProcess/CoeffConv/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/CoeffConv/CoeffConv.exe" "PreProcess/CoeffConv/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/CoeffConv/CoeffConvExample.coi" "PreProcess/CoeffConv/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/CoeffConv/EPL-Check.BAT" "PreProcess/CoeffConv/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/CoeffConv/EPL-Conv.BAT" "PreProcess/CoeffConv/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/CoeffConv/ReadMe.txt" "PreProcess/CoeffConv/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/GrndTempCalc/RunBasement.bat" "PreProcess/GrndTempCalc/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/GrndTempCalc/RunSlab.bat" "PreProcess/GrndTempCalc/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/HVACCurveFitTool/CurveFitTool.xlsm" "PreProcess/HVACCurveFitTool/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/IDFEditor/IDFEditor.exe" "PreProcess/IDFEditor/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/ParametricPreProcessor/RunParam.bat" "PreProcess/ParametricPreProcessor/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/ViewFactorCalculation/readme.txt" "PreProcess/ViewFactorCalculation/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/ViewFactorCalculation/View3D.exe" "PreProcess/ViewFactorCalculation/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/ViewFactorCalculation/View3D32.pdf" "PreProcess/ViewFactorCalculation/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/ViewFactorCalculation/ViewFactorInterface.xls" "PreProcess/ViewFactorCalculation/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/Abbreviations.csv" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/ASHRAE_2013_Monthly_DesignConditions.csv" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/ASHRAE_2013_OtherMonthly_DesignConditions.csv" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/ASHRAE_2013_Yearly_DesignConditions.csv" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/Cal%20Climate%20Zone%20Lat%20Long%20data.csv" "PreProcess/WeatherConverter/" "Cal Climate Zone Lat Long data.csv")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/CountryCodes.txt" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/EPlusWth.dll" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/libifcoremd.dll" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/libifportmd.dll" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/libmmd.dll" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/svml_dispmd.dll" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/TimeZoneCodes.txt" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/WBANLocations.csv" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/Windows/PreProcess/WeatherConverter/Weather.exe" "PreProcess/WeatherConverter/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Win/EP-Compare%20Libs/Appearance%20Pak.dll" "PostProcess/EP-Compare/EP-Compare Libs/" "Appearance Pak.dll")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Win/EP-Compare%20Libs/EHInterfaces5001.dll" "PostProcess/EP-Compare/EP-Compare Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Win/EP-Compare%20Libs/EHObjectArray5001.dll" "PostProcess/EP-Compare/EP-Compare Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Win/EP-Compare%20Libs/EHObjectCollection5001.dll" "PostProcess/EP-Compare/EP-Compare Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Win/EP-Compare%20Libs/EHTreeView4301.DLL" "PostProcess/EP-Compare/EP-Compare Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Win/EP-Compare%20Libs/MBSChartDirector5Plugin16042.dll" "PostProcess/EP-Compare/EP-Compare Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Win/EP-Compare.exe" "PostProcess/EP-Compare/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/GraphHints.csv" "PostProcess/EP-Compare/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EPDraw/Run-Win/EPDrawGUI%20Libs/Appearance%20Pak.dll" "PreProcess/EPDraw/EPDrawGUI Libs/" "Appearance Pak.dll")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EPDraw/Run-Win/EPDrawGUI%20Libs/Shell.dll" "PreProcess/EPDraw/EPDrawGUI Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EPDraw/Run-Win/EPDrawGUI.exe" "PreProcess/EPDraw/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EPDraw/Run-Win/EPlusDrw.dll" "PreProcess/EPDraw/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EPDraw/Run-Win/libifcoremd.dll" "PreProcess/EPDraw/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EPDraw/Run-Win/libifportmd.dll" "PreProcess/EPDraw/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EPDraw/Run-Win/libmmd.dll" "PreProcess/EPDraw/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EPDraw/Run-Win/svml_dispmd.dll" "PreProcess/EPDraw/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/GrndTempCalc/basementexample.audit" "PreProcess/GrndTempCalc/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/GrndTempCalc/basementexample.csv" "PreProcess/GrndTempCalc/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/GrndTempCalc/BasementExample.idf" "PreProcess/GrndTempCalc/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/GrndTempCalc/basementexample.out" "PreProcess/GrndTempCalc/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/GrndTempCalc/basementexample_out.idf" "PreProcess/GrndTempCalc/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/GrndTempCalc/slabexample.ger" "PreProcess/GrndTempCalc/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/GrndTempCalc/slabexample.gtp" "PreProcess/GrndTempCalc/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/GrndTempCalc/SlabExample.idf" "PreProcess/GrndTempCalc/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/IDFVersionUpdater/Run-Win/IDFVersionUpdater%20Libs/Appearance%20Pak.dll" "PreProcess/IDFVersionUpdater/IDFVersionUpdater Libs/" "Appearance Pak.dll")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/IDFVersionUpdater/Run-Win/IDFVersionUpdater%20Libs/RBGUIFramework.dll" "PreProcess/IDFVersionUpdater/IDFVersionUpdater Libs/" "RBGUIFramework.dll")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/IDFVersionUpdater/Run-Win/IDFVersionUpdater%20Libs/msvcp120.dll" "PreProcess/IDFVersionUpdater/IDFVersionUpdater Libs/" "msvcp120.dll")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/IDFVersionUpdater/Run-Win/IDFVersionUpdater%20Libs/msvcr120.dll" "PreProcess/IDFVersionUpdater/IDFVersionUpdater Libs/" "msvcr120.dll")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/IDFVersionUpdater/Run-Win/IDFVersionUpdater%20Libs/Shell.dll" "PreProcess/IDFVersionUpdater/IDFVersionUpdater Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/IDFVersionUpdater/Run-Win/IDFVersionUpdater.exe" "PreProcess/IDFVersionUpdater/")
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/EPMacro/Windows/EPMacro.exe" "./")
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/Windows/System/ComDlg32.OCX" "./temp/")
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/Windows/System/Dforrt.dll" "./temp/")
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/Windows/System/Graph32.ocx" "./temp/")
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/Windows/System/Gsw32.exe" "./temp/")
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/Windows/System/Gswdll32.dll" "./temp/")
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/Windows/System/MSCOMCTL.OCX" "./temp/")
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/Windows/System/Msflxgrd.ocx" "./temp/")
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/Windows/System/MSINET.OCX" "./temp/")
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/Windows/System/Msvcrtd.dll" "./temp/")
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/Windows/System/Vsflex7L.ocx" "./temp/")
endif()

if( APPLE )
  set(CPACK_PACKAGE_DEFAULT_LOCATION "/Applications")
  install(DIRECTORY "${BUILDSUPPORTDIR}/bin/Mac/EP-Launch_Lite/build/Release/EP-Launch Lite.app" DESTINATION "./")
  install(DIRECTORY "${BUILDSUPPORTDIR}/bin/IDFVersionUpdater/Run-Mac/IDFVersionUpdater.app" DESTINATION "PreProcess/IDFVersionUpdater")
  install(DIRECTORY "${BUILDSUPPORTDIR}/bin/Mac/Uninstall EnergyPlus.app" DESTINATION "./")
  install(DIRECTORY "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Mac/EP-Compare.app" DESTINATION "PostProcess/EP-Compare")
  install(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/GraphHints.csv" DESTINATION "PostProcess/EP-Compare/")
  install(PROGRAMS "${BUILDSUPPORTDIR}/bin/EPMacro/Mac/EPMacro" DESTINATION "./")

  configure_file(scripts/runenergyplus.in "${CMAKE_BINARY_DIR}/scripts/runenergyplus" @ONLY)
  install(PROGRAMS "${CMAKE_BINARY_DIR}/scripts/runenergyplus" DESTINATION "./")
  install(PROGRAMS scripts/runepmacro DESTINATION "./")
  install(PROGRAMS scripts/runreadvars DESTINATION "./")

  configure_file("${PROJECT_SOURCE_DIR}/cmake/darwinpostflight.sh.in" ${CMAKE_BINARY_DIR}/darwinpostflight.sh)
  set(CPACK_POSTFLIGHT_SCRIPT "${CMAKE_BINARY_DIR}/darwinpostflight.sh")
endif()

if( UNIX)
  install(FILES doc/man/energyplus.1 DESTINATION "./")
endif()

if( UNIX AND NOT APPLE )
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Linux/EP-Compare" "PostProcess/EP-Compare/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Linux/EP-Compare%20Libs/EHInterfaces5001.so" "PostProcess/EP-Compare/EP-Compare Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Linux/EP-Compare%20Libs/EHObjectArray5001.so" "PostProcess/EP-Compare/EP-Compare Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Linux/EP-Compare%20Libs/EHObjectCollection5001.so" "PostProcess/EP-Compare/EP-Compare Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Linux/EP-Compare%20Libs/EHTreeView4301.so" "PostProcess/EP-Compare/EP-Compare Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Linux/EP-Compare%20Libs/libMBSChartDirector5Plugin16042.so" "PostProcess/EP-Compare/EP-Compare Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/EP-Compare/Run-Linux/EP-Compare%20Libs/libRBAppearancePak.so" "PostProcess/EP-Compare/EP-Compare Libs/")

  install_remote(FILES "${BUILDSUPPORTDIR}/bin/IDFVersionUpdater/Run-Linux/IDFVersionUpdater%20Libs/libRBAppearancePak.so" "PreProcess/IDFVersionUpdater/IDFVersionUpdater Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/IDFVersionUpdater/Run-Linux/IDFVersionUpdater%20Libs/libRBShell.so" "PreProcess/IDFVersionUpdater/IDFVersionUpdater Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/IDFVersionUpdater/Run-Linux/IDFVersionUpdater%20Libs/RBGUIFramework.so" "PreProcess/IDFVersionUpdater/IDFVersionUpdater Libs/")
  install_remote(FILES "${BUILDSUPPORTDIR}/bin/IDFVersionUpdater/Run-Linux/IDFVersionUpdater%20Libs/libc++.so.1" "PreProcess/IDFVersionUpdater/IDFVersionUpdater Libs/")
  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/IDFVersionUpdater/Run-Linux/IDFVersionUpdater" "PreProcess/IDFVersionUpdater/")

  install_remote(PROGRAMS "${BUILDSUPPORTDIR}/bin/EPMacro/Linux/EPMacro" "./")

  configure_file(scripts/runenergyplus.in "${CMAKE_BINARY_DIR}/scripts/runenergyplus" @ONLY)
  install(PROGRAMS "${CMAKE_BINARY_DIR}/scripts/runenergyplus" DESTINATION "./")
  install(PROGRAMS scripts/runepmacro DESTINATION "./")
  install(PROGRAMS scripts/runreadvars DESTINATION "./")
endif()

configure_file("${CMAKE_SOURCE_DIR}/cmake/CMakeCPackOptions.cmake.in"
  "${CMAKE_BINARY_DIR}/CMakeCPackOptions.cmake" @ONLY)
set(CPACK_PROJECT_CONFIG_FILE "${CMAKE_BINARY_DIR}/CMakeCPackOptions.cmake")

if ( BUILD_DOCS )
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/Acknowledgements.pdf" DESTINATION "./Documentation")
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/AuxiliaryPrograms.pdf" DESTINATION "./Documentation")
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/EMSApplicationGuide.pdf" DESTINATION "./Documentation")
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/EngineeringReference.pdf" DESTINATION "./Documentation")
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/ExternalInterfacesApplicationGuide.pdf" DESTINATION "./Documentation")
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/GettingStarted.pdf" DESTINATION "./Documentation")
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/InputOutputReference.pdf" DESTINATION "./Documentation")
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/InterfaceDeveloper.pdf" DESTINATION "./Documentation")
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/ModuleDeveloper.pdf" DESTINATION "./Documentation")
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/OutputDetailsAndExamples.pdf" DESTINATION "./Documentation")
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/PlantApplicationGuide.pdf" DESTINATION "./Documentation")
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/TipsAndTricksUsingEnergyPlus.pdf" DESTINATION "./Documentation")
	install(FILES "${CMAKE_BINARY_DIR}/doc-build/UsingEnergyPlusForCompliance.pdf" DESTINATION "./Documentation")
endif ()

INCLUDE(CPack)

