// EnergyPlus, Copyright (c) 1996-2016, The Board of Trustees of the University of Illinois and
// The Regents of the University of California, through Lawrence Berkeley National Laboratory
// (subject to receipt of any required approvals from the U.S. Dept. of Energy). All rights
// reserved.
//
// If you have questions about your rights to use or distribute this software, please contact
// Berkeley Lab's Innovation & Partnerships Office at IPO@lbl.gov.
//
// NOTICE: This Software was developed under funding from the U.S. Department of Energy and the
// U.S. Government consequently retains certain rights. As such, the U.S. Government has been
// granted for itself and others acting on its behalf a paid-up, nonexclusive, irrevocable,
// worldwide license in the Software to reproduce, distribute copies to the public, prepare
// derivative works, and perform publicly and display publicly, and to permit others to do so.
//
// Redistribution and use in source and binary forms, with or without modification, are permitted
// provided that the following conditions are met:
//
// (1) Redistributions of source code must retain the above copyright notice, this list of
//     conditions and the following disclaimer.
//
// (2) Redistributions in binary form must reproduce the above copyright notice, this list of
//     conditions and the following disclaimer in the documentation and/or other materials
//     provided with the distribution.
//
// (3) Neither the name of the University of California, Lawrence Berkeley National Laboratory,
//     the University of Illinois, U.S. Dept. of Energy nor the names of its contributors may be
//     used to endorse or promote products derived from this software without specific prior
//     written permission.
//
// (4) Use of EnergyPlus(TM) Name. If Licensee (i) distributes the software in stand-alone form
//     without changes from the version obtained under this License, or (ii) Licensee makes a
//     reference solely to the software portion of its product, Licensee must refer to the
//     software as "EnergyPlus version X" software, where "X" is the version number Licensee
//     obtained under this License and may not use a different name for the software. Except as
//     specifically required in this Section (4), Licensee shall not use in a company name, a
//     product name, in advertising, publicity, or other promotional activities any name, trade
//     name, trademark, logo, or other designation of "EnergyPlus", "E+", "e+" or confusingly
//     similar designation, without Lawrence Berkeley National Laboratory's prior written consent.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
// AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//
// You are under no obligation whatsoever to provide any bug fixes, patches, or upgrades to the
// features, functionality or performance of the source code ("Enhancements") to anyone; however,
// if you choose to make your Enhancements available either publicly, or directly to Lawrence
// Berkeley National Laboratory, without imposing a separate written license agreement for such
// Enhancements, then you hereby grant the following license: a non-exclusive, royalty-free
// perpetual license to install, use, modify, prepare derivative works, incorporate into other
// computer software, distribute, and sublicense such enhancements or derivative works thereof,
// in binary and source code form.

// EnergyPlus::VariableSpeedCoils Unit Tests

// Google Test Headers
#include <gtest/gtest.h>
#include "Fixtures/EnergyPlusFixture.hh"
#include <ObjexxFCL/Array1D.hh>
#include <EnergyPlus/OutputProcessor.hh>
#include <EnergyPlus/SimulationManager.hh>
#include <EnergyPlus/VariableSpeedCoils.hh>

using namespace EnergyPlus;
using namespace EnergyPlus::SimulationManager;
using namespace ObjexxFCL;

namespace EnergyPlus {


	TEST_F( EnergyPlusFixture, PackagedTerminalHPVSCoils ) {
		std::string const idf_objects = delimited_string({

		" Timestep, 4;",
		" BUILDING, OutputReportTabular_ZoneMultiplierTest, 0.0, Suburbs, .04, .4, FullExterior, 25, 6;",
		" SimulationControl, YES, NO, NO, YES, NO;",
		" Site:Location, Miami, 25.82, -80.30, -5.00, 11; ",
		" SizingPeriod:DesignDay, Clg DB/MCWB, 7, 21, SummerDesignDay, 31.7, 10.0, , , Wetbulb, 22.7, , , , , 101217., 3.8, 340, No, No, No, ASHRAEClearSky, , , , , 1.00; ",
		" SizingPeriod:DesignDay, Htg99.6% DB, 1, 21, WinterDesignDay,  8.7,  0.0, , , Wetbulb,  8.7, , , , , 101217., 3.8, 340, No, No, No, ASHRAEClearSky, , , , , 0.00; ",
		" Zone, Space, 0.0, 0.0, 0.0, 0.0, 1, 1, 2.4, , autocalculate, , , Yes; ",
		" Sizing:Zone, Space, SupplyAirTemperature, 12., , SupplyAirTemperature, 50., , 0.008, 0.008, SZ DSOA, 0.0, 0.0, DesignDay, 0, , , , DesignDay, 0, , , ; ",
		" DesignSpecification:OutdoorAir, SZ DSOA, flow/person, 0.00944, 0.0, 0.0; ",
		" ZoneHVAC:EquipmentConnections, Space, Space Eq, Space In Node, Space Out Node, Space Node, Space Ret Node; ",
		" ZoneHVAC:EquipmentList, Space Eq, ZoneHVAC:WindowAirConditioner, WindAC, 1, 1; ",
		" People, Space People, Space, OnSched, people, 11, , , 0.3, AutoCalculate, OnSched; ",
		" Schedule:Compact, OnSched, Fraction, Through: 12/31, For: AllDays, Until: 24:00, 1.0; ",
		" ScheduleTypeLimits, Fraction, 0.0, 1.0, CONTINUOUS; ",

		"  Coil:Cooling:DX:VariableSpeed,",
		"    PSZ-AC_1:5_CoolC Standard 4-compressor IPAK,  !- Name",
		"    PSZ-AC_1:5_OA-PSZ-AC_1:5_CoolCNode,  !- Air Inlet Node Name",
		"    PSZ-AC_1:5_CoolC-PSZ-AC_1:5_HeatCNode,  !- Air Outlet Node Name",
		"    5,                      !- Number of Speeds {dimensionless}",
		"    5,                       !- Nominal Speed Level {dimensionless}",
		"    autosize,                !- Rated Total Cooling Capacity At Selected Nominal Speed Level {w}",
		"    autosize,                !- Rated Volumetric Air Flow Rate At Selected Nominal Speed Level {m3/s}",
		"    0,                       !- Nominal Time for Condensate to Begin Leaving the Coil {s}",
		"    0,                       !- Initial Moisture Evaporation Rate Divided by Steady-State AC Latent Capacity {dimensionless}",
		"    PLF Curve,               !- Energy Part Load Fraction Curve Name",
		"    PSZ-AC_1:5 OA Node,           !- Condenser Air Inlet Node Name",
		"    AirCooled,               !- Condenser Type",
		"    ,                        !- Evaporative Condenser Pump Rated Power Consumption {W}",
		"    ,                        !- Crankcase Heater Capacity {W}",
		"    10,                      !- Maximum Outdoor Dry-Bulb Temperature for Crankcase Heater Operation {C}",
		"    ,                        !- Supply Water Storage Tank Name",
		"    ,                        !- Condensate Collection Water Storage Tank Name",
		"    ,                        !- Basin Heater Capacity {W/K}",
		"    2,                       !- Basin Heater Setpoint Temperature {C}",
		"    ,                        !- Basin Heater Operating Schedule Name",
		"    33861.72,             !- Speed 1 Reference Unit Total Cooling Capacity At Rated Conditions {w}",
		"    0.70,               !- Speed 1 Reference Unit Sensible Heat Ratio At Rated Conditions {dimensionless}",
		"    4.328973,             !- Speed 1 Reference Unit COP At Rated Conditions {dimensionless}",
		"    1.396964,              !- Speed 1 Reference Unit Air Flow Rate At Rated Conditions {m3/s}",
		"    ,                        !- Speed 1 Reference Unit Condenser Flow Rate at Rated Conditions {m3/s}",
		"    ,                        !- Speed 1 Reference Unit Pad Effectiveness of Evap Precooling at Rated Conditions {dimensionless}",
		"    BiquadraticCurve,         !- Speed 1 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,             !- Speed 1 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    BiquadraticCurve,            !- Speed 1 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,             !- Speed 1 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    35516.08,             !- Speed 2 Reference Unit Total Cooling Capacity At Rated Conditions {w}",
		"    0.78,              !- Speed 2 Reference Unit Sensible Heat Ratio At Rated Conditions {dimensionless}",
		"    4.540061,             !- Speed 2 Reference Unit COP At Rated Conditions {dimensionless}",
		"    1.88779,              !- Speed 2 Reference Unit Air Flow Rate At Rated Conditions {m3/s}",
		"    ,                        !- Speed 2 Reference Unit Condenser Flow Rate at Rated Conditions {m3/s}",
		"    ,                        !- Speed 2 Reference Unit Pad Effectiveness of Evap Precooling at Rated Conditions {dimensionless}",
		"    BiquadraticCurve,          !- Speed 2 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,             !- Speed 2 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    BiquadraticCurve,             !- Speed 2 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,             !- Speed 2 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    65133.17,             !- Speed 3 Reference Unit Total Cooling Capacity At Rated Conditions {w}",
		"    0.70,             !- Speed 3 Reference Unit Sensible Heat Ratio At Rated Conditions {dimensionless}",
		"    4.164418,             !- Speed 3 Reference Unit COP At Rated Conditions {dimensionless}",
		"    2.831685,              !- Speed 3 Reference Unit Air Flow Rate At Rated Conditions {m3/s}",
		"    ,                        !- Speed 3 Reference Unit Condenser Flow Rate at Rated Conditions {m3/s}",
		"    ,                        !- Speed 3 Reference Unit Pad Effectiveness of Evap Precooling at Rated Conditions {dimensionless}",
		"    BiquadraticCurve,          !- Speed 3 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,             !- Speed 3 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    BiquadraticCurve,             !- Speed 3 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,             !- Speed 3 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    119583.3,             !- Speed 4 Reference Unit Total Cooling Capacity At Rated Conditions {w}",
		"    0.62,              !- Speed 4 Reference Unit Sensible Heat Ratio At Rated Conditions {dimensionless}",
		"    3.469661,             !- Speed 4 Reference Unit COP At Rated Conditions {dimensionless}",
		"    3.553764,              !- Speed 4 Reference Unit Air Flow Rate At Rated Conditions {m3/s}",
		"    ,                        !- Speed 4 Reference Unit Condenser Flow Rate at Rated Conditions {m3/s}",
		"    ,                        !- Speed 4 Reference Unit Pad Effectiveness of Evap Precooling at Rated Conditions {dimensionless}",
		"    BiquadraticCurve,          !- Speed 4 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,             !- Speed 4 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    BiquadraticCurve,             !- Speed 4 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,             !- Speed 4 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    132769.7,             !- Speed 5 Reference Unit Total Cooling Capacity At Rated Conditions {w}",
		"    0.69,             !- Speed 5 Reference Unit Sensible Heat Ratio At Rated Conditions {dimensionless}",
		"    3.822957,             !- Speed 5 Reference Unit COP At Rated Conditions {dimensionless}",
		"    5.66336932,              !- Speed 5 Reference Unit Air Flow Rate At Rated Conditions {m3/s}",
		"    ,                        !- Speed 5 Reference Unit Condenser Flow Rate at Rated Conditions {m3/s}",
		"    ,                        !- Speed 5 Reference Unit Pad Effectiveness of Evap Precooling at Rated Conditions {dimensionless}",
		"    BiquadraticCurve,          !- Speed 5 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,             !- Speed 5 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    BiquadraticCurve,             !- Speed 5 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve;             !- Speed 5 Energy Input Ratio Function of Air Flow Fraction Curve Name",

		"  ZoneHVAC:WaterToAirHeatPump,",
		"    Lobby_ZN_1_FLR_2 WSHP,              !- Name",
		"    HVACOperationSchd,    !- Availability Schedule Name",
		"    Lobby_ZN_1_FLR_2 WSHP Inlet Node,      !- Air Inlet Node Name",
		"    Lobby_ZN_1_FLR_2 WSHP Outlet Node,       !- Air Outlet Node Name",
		"    ,        !- Outdoor Air Mixer Object Type",
		"    ,            !- Outdoor Air Mixer Name",
		"    Autosize,                !- Supply Air Flow Rate During Cooling Operation {m3/s}",
		"    Autosize,                !- Supply Air Flow Rate During Heating Operation {m3/s}",
		"    ,                     !- Supply Air Flow Rate When No Cooling or Heating is Needed {m3/s}",
		"    0.0,                     !- Outdoor Air Flow Rate During Cooling Operation {m3/s}",
		"    0.0,                     !- Outdoor Air Flow Rate During Heating Operation {m3/s}",
		"    ,                        !- Outdoor Air Flow Rate When No Cooling or Heating is Needed {m3/s}",
		"    Fan:OnOff,               !- Supply Air Fan Object Type",
		"    Lobby_ZN_1_FLR_2 WSHP Fan,              !- Supply Air Fan Name",
		"    Coil:Heating:WaterToAirHeatPump:VariableSpeedEquationFit,  !- Heating Coil Object Type",
		"    Lobby_ZN_1_FLR_2 WSHP Heating Mode,  !- Heating Coil Name",
		"    Coil:Cooling:WaterToAirHeatPump:VariableSpeedEquationFit,  !- Cooling Coil Object Type",
		"    Lobby_ZN_1_FLR_2 WSHP Cooling Mode,  !- Cooling Coil Name",
		"    2.5,                     !- Maximum Cycling Rate {cycles/hr}",
		"    60.0,                    !- Heat Pump Time Constant {s}",
		"    0.01,                    !- Fraction of On-Cycle Power Use",
		"    60,                      !- Heat Pump Fan Delay Time {s}",
		"    Coil:Heating:Electric,        !- Supplemental Heating Coil Object Type",
		"    Lobby_ZN_1_FLR_2 WSHP Supp Heating Coil,  !- Supplemental Heating Coil Name",
		"    50.0,                    !- Maximum Supply Air Temperature from Supplemental Heater {C}",
		"    20.0,                    !- Maximum Outdoor Dry-Bulb Temperature for Supplemental Heater Operation {C}",
		"    Lobby_ZN_1_FLR_2 WSHP OA Node,  !- Outdoor Dry-Bulb Temperature Sensor Node Name",
		"    BlowThrough,             !- Fan Placement",
		"    CyclingFanSch,           !- Supply Air Fan Operating Mode Schedule Name",
		"    ,!- Heat Pump Coil Water Flow Mode",
		"    ;!- Design Specification ZoneHVAC Sizing Object Name",

		"  Coil:Cooling:WaterToAirHeatPump:VariableSpeedEquationFit,",
		"    Lobby_ZN_1_FLR_2 WSHP Cooling Mode,  !- Name",
		"    Lobby_ZN_1_FLR_2 WSHP Cooling Source Side Inlet Node,  !- Water-to-Refrigerant HX Water Inlet Node Name",
		"    Lobby_ZN_1_FLR_2 WSHP Cooling Source Side Outlet Node,  !- Water-to-Refrigerant HX Water Outlet Node Name",
		"    Lobby_ZN_1_FLR_2 WSHP Cooling Coil Air Inlet Node,  !- Indoor Air Inlet Node Name",
		"    Lobby_ZN_1_FLR_2 WSHP Heating Coil Air Inlet Node,  !- Indoor Air Outlet Node Name",
		"    9,                    !- Number of Speeds {dimensionless}",
		"    9,                      !- Nominal Speed Level {dimensionless}",
		"    Autosize,                !- Gross Rated Total Cooling Capacity At Selected Nominal Speed Level {w}",
		"    Autosize,                !- Rated Air Flow Rate At Selected Nominal Speed Level {m3/s}",
		"    Autosize,                !- Rated Water Flow Rate At Selected Nominal Speed Level {m3/s}",
		"    0.0,                     !- Nominal Time for Condensate to Begin Leaving the Coil {s}",
		"    0.0,                     !- Initial Moisture Evaporation Rate Divided by Steady-State AC Latent Capacity {dimensionless}",
		"    0,                       !- Flag for Using Hot Gas Reheat, 0 or 1 {dimensionless}",
		"    PLF Curve,               !- Energy Part Load Fraction Curve Name",
		"    4682.3964854,            !- Speed 1 Reference Unit Gross Rated Total Cooling Capacity {w}",
		"    0.97,                    !- Speed 1 Reference Unit Gross Rated Sensible Heat Ratio {dimensionless}",
		"    8.031554863,             !- Speed 1 Reference Unit Gross Rated Cooling COP {dimensionless}",
		"    0.408706486,             !- Speed 1 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 1 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,  !- Speed 1 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 1 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 1 Total Cooling Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,   !- Speed 1 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 1 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 1 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 1 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 1 Waste Heat Function of Temperature Curve Name",
		"    5733.6424135,            !- Speed 2 Reference Unit Gross Rated Total Cooling Capacity {w}",
		"    0.96,                  !- Speed 2 Reference Unit Gross Rated Sensible Heat Ratio {dimensionless}",
		"    8.132826118,             !- Speed 2 Reference Unit Gross Rated Cooling COP {dimensionless}",
		"    0.449293966,               !- Speed 2 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 2 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,   !- Speed 2 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 2 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 2 Total Cooling Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,   !- Speed 2 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 2 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 2 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 2 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 2 Waste Heat Function of Temperature Curve Name",
		"    6783.7160573,             !- Speed 3 Reference Unit Gross Rated Total Cooling Capacity {w}",
		"    0.95,                   !- Speed 3 Reference Unit Gross Rated Sensible Heat Ratio {dimensionless}",
		"    8.133952107,             !- Speed 3 Reference Unit Gross Rated Cooling COP {dimensionless}",
		"    0.489881446,              !- Speed 3 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 3 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,   !- Speed 3 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 3 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,    !- Speed 3 Total Cooling Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,   !- Speed 3 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,     !- Speed 3 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 3 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 3 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 3 Waste Heat Function of Temperature Curve Name",
		"    7819.1361476,            !- Speed 4 Reference Unit Gross Rated Total Cooling Capacity {w}",
		"    0.91,                   !- Speed 4 Reference Unit Gross Rated Sensible Heat Ratio {dimensionless}",
		"    8.077619987,             !- Speed 4 Reference Unit Gross Rated Cooling COP {dimensionless}",
		"    0.530468926,             !- Speed 4 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 4 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,   !- Speed 4 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 4 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 4 Total Cooling Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,   !- Speed 4 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 4 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 4 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 4 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 4 Waste Heat Function of Temperature Curve Name",
		"    8827.8867705,             !- Speed 5 Reference Unit Gross Rated Total Cooling Capacity {w}",
		"    0.871,                   !- Speed 5 Reference Unit Gross Rated Sensible Heat Ratio {dimensionless}",
		"    7.974604129,             !- Speed 5 Reference Unit Gross Rated Cooling COP {dimensionless}",
		"    0.571056406,             !- Speed 5 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 5 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,   !- Speed 5 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,     !- Speed 5 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,    !- Speed 5 Total Cooling Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,   !- Speed 5 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 5 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 5 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 5 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 5 Waste Heat Function of Temperature Curve Name",
		"    10734.02101,            !- Speed 6 Reference Unit Gross Rated Total Cooling Capacity {w}",
		"    0.816,                   !- Speed 6 Reference Unit Gross Rated Sensible Heat Ratio {dimensionless}",	
		"    7.661685232,             !- Speed 6 Reference Unit Gross Rated Cooling COP {dimensionless}",
		"    0.652231367,             !- Speed 6 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 6 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,   !- Speed 6 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 6 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 6 Total Cooling Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,   !- Speed 6 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 6 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 6 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 6 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve ,                        !- Speed 6 Waste Heat Function of Temperature Curve Name",
		"    12454.348191,            !- Speed 7 Reference Unit Gross Rated Total Cooling Capacity {w}",
		"    0.784,                    !- Speed 7 Reference Unit Gross Rated Sensible Heat Ratio {dimensionless}",
		"    7.257778666,             !- Speed 7 Reference Unit Gross Rated Cooling COP {dimensionless}",
		"    0.732934379,             !- Speed 7 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 7 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,   !- Speed 7 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 7 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 7 Total Cooling Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,   !- Speed 7 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 7 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 7 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 7 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 7 Waste Heat Function of Temperature Curve Name",
		"    13963.37113,            !- Speed 8 Reference Unit Gross Rated Total Cooling Capacity {w}",
		"    0.766,                   !- Speed 8 Reference Unit Gross Rated Sensible Heat Ratio {dimensionless}",
		"    6.804761759,             !- Speed 8 Reference Unit Gross Rated Cooling COP {dimensionless}",
		"    0.81410934,             !- Speed 8 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 8 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,   !- Speed 8 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 8 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 8 Total Cooling Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,   !- Speed 8 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 8 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 8 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 8 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 8 Waste Heat Function of Temperature Curve Name",
		"    16092.825525,            !- Speed 9 Reference Unit Gross Rated Total Cooling Capacity {w}",
		"    0.739,                   !- Speed 9 Reference Unit Gross Rated Sensible Heat Ratio {dimensionless}",
		"    5.765971166,             !- Speed 9 Reference Unit Gross Rated Cooling COP {dimensionless}",
		"    0.891980668,             !- Speed 9 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 9 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,   !- Speed 9 Total Cooling Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 9 Total Cooling Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 9 Total Cooling Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,   !- Speed 9 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 9 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 9 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 9 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve;                        !- Speed 9 Waste Heat Function of Temperature Curve Name",
    
		"  Coil:Heating:WaterToAirHeatPump:VariableSpeedEquationFit,",
		"    Lobby_ZN_1_FLR_2 WSHP Heating Mode,  !- Name",
		"    Lobby_ZN_1_FLR_2 WSHP Heating Source Side Inlet Node,  !- Water-to-Refrigerant HX Water Inlet Node Name",
		"    Lobby_ZN_1_FLR_2 WSHP Heating Source Side Outlet Node,  !- Water-to-Refrigerant HX Water Outlet Node Name",
		"    Lobby_ZN_1_FLR_2 WSHP Heating Coil Air Inlet Node,  !- Indoor Air Inlet Node Name",
		"    Lobby_ZN_1_FLR_2 WSHP SuppHeating Coil Air Inlet Node,  !- Indoor Air Outlet Node Name",
		"    9,                      !- Number of Speeds {dimensionless}",
		"    9,                       !- Nominal Speed Level {dimensionless}",
		"    autosize,                !- Rated Heating Capacity At Selected Nominal Speed Level {w}",
		"    autosize,                !- Rated Air Flow Rate At Selected Nominal Speed Level {m3/s}",
		"    autosize,                !- Rated Water Flow Rate At Selected Nominal Speed Level {m3/s}",
		"    PLF Curve,               !- Energy Part Load Fraction Curve Name",
		"    6437.5991236,            !- Speed 1 Reference Unit Gross Rated Heating Capacity {w}",
		"    9.965323721,              !- Speed 1 Reference Unit Gross Rated Heating COP {dimensionless}",
		"    0.408706486,             !- Speed 1 Reference Unit Rated Air Flow {m3/s}",
		"    0.0008201726 ,                  !- Speed 1 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,        !- Speed 1 Heating Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 1 Total  Heating Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 1 Heating Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,  !- Speed 1 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 1 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 1 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 1 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 1 Waste Heat Function of Temperature Curve Name",
		"    7521.3759405,            !- Speed 2 Reference Unit Gross Rated Heating Capacity {w}",
		"    9.3549452,             !- Speed 2 Reference Unit Gross Rated Heating COP {dimensionless}",
		"    0.449293966,               !- Speed 2 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 2 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,        !- Speed 2 Heating Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 2 Total  Heating Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 2 Heating Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,        !- Speed 2 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 2 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 2 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 2 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 2 Waste Heat Function of Temperature Curve Name",
		"    8601.0497624,              !- Speed 3 Reference Unit Gross Rated Heating Capacity {w}",
		"    8.857929724,             !- Speed 3 Reference Unit Gross Rated Heating COP {dimensionless}",
		"    0.489881446,              !- Speed 3 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 3 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,   !- Speed 3 Heating Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 3 Total  Heating Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 3 Heating Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,  !- Speed 3 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 3 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 3 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 3 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 3 Waste Heat Function of Temperature Curve Name",
		"    9675.1552339,            !- Speed 4 Reference Unit Gross Rated Heating Capacity {w}",
		"    8.442543834,             !- Speed 4 Reference Unit Gross Rated Heating COP {dimensionless}",
		"    0.530468926,             !- Speed 4 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 4 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,   !- Speed 4 Heating Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 4 Total  Heating Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 4 Heating Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,  !- Speed 4 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 4 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 4 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 4 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 4 Waste Heat Function of Temperature Curve Name",
		"    10743.692355,            !- Speed 5 Reference Unit Gross Rated Heating Capacity {w}",
		"    8.090129785,             !- Speed 5 Reference Unit Gross Rated Heating COP {dimensionless}",
		"    0.571056406,             !- Speed 5 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 5 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,    !- Speed 5 Heating Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 5 Total  Heating Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 5 Heating Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,  !- Speed 5 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 5 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 5 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 5 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 5 Waste Heat Function of Temperature Curve Name",
		"    12861.716978,            !- Speed 6 Reference Unit Gross Rated Heating Capacity {w}",
		"    7.521471917,             !- Speed 6 Reference Unit Gross Rated Heating COP {dimensionless}",
		"    0.652231367,             !- Speed 6 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 6 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,     !- Speed 6 Heating Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 6 Total  Heating Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 6 Heating Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,    !- Speed 6 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 6 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 6 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 6 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 6 Waste Heat Function of Temperature Curve Name",
		"    14951.606778,            !- Speed 7 Reference Unit Gross Rated Heating Capacity {w}",
		"    7.072661674,             !- Speed 7 Reference Unit Gross Rated Heating COP {dimensionless}",
		"    0.732934379,             !- Speed 7 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 7 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,   !- Speed 7 Heating Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 7 Total  Heating Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 7 Heating Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,  !- Speed 7 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 7 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 7 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 7 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 7 Waste Heat Function of Temperature Curve Name",
		"    17011.8964,            !- Speed 8 Reference Unit Gross Rated Heating Capacity {w}",
		"    6.710807258,             !- Speed 8 Reference Unit Gross Rated Heating COP {dimensionless}",
		"    0.81410934,             !- Speed 8 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 8 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,    !- Speed 8 Heating Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 8 Total  Heating Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 8 Heating Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,  !- Speed 8 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 8 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 8 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0 ,                        !- Speed 8 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve,                        !- Speed 8 Waste Heat Function of Temperature Curve Name",
		"    20894.501936,            !- Speed 9 Reference Unit Gross Rated Heating Capacity {w}",
		"    5.89906887,               !- Speed 9 Reference Unit Gross Rated Heating COP {dimensionless}",
		"    0.891980668,             !- Speed 9 Reference Unit Rated Air Flow Rate {m3/s}",
		"    0.0008201726 ,                  !- Speed 9 Reference Unit Rated Water Flow Rate {m3/s}",
		"    BiquadraticCurve,  !- Speed 9 Heating Capacity Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 9 Total  Heating Capacity Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 9 Heating Capacity Function of Water Flow Fraction Curve Name",
		"    BiquadraticCurve,  !- Speed 9 Energy Input Ratio Function of Temperature Curve Name",
		"    CubicCurve,      !- Speed 9 Energy Input Ratio Function of Air Flow Fraction Curve Name",
		"    CubicCurve,      !- Speed 9 Energy Input Ratio Function of Water Flow Fraction Curve Name",
		"    0.0,                        !- Speed 9 Reference Unit Waste Heat Fraction of Input Power At Rated Conditions {dimensionless}",
		"    BiquadraticCurve;                        !- Speed 9 Waste Heat Function of Temperature Curve Name",
 
		"  Fan:OnOff,",
		"    Lobby_ZN_1_FLR_2 WSHP Fan,              !- Name",
		"    ALWAYS_ON,    !- Availability Schedule Name",
		"    0.7,                     !- Fan Total Efficiency",
		"    113,                   !- Pressure Rise {Pa}",
		"    Autosize,                !- Maximum Flow Rate {m3/s}",
		"    0.9,                     !- Motor Efficiency",
		"    1.0,                     !- Motor In Airstream Fraction",
		"    Lobby_ZN_1_FLR_2 WSHP Inlet Node,    !- Air Inlet Node Name",
		"    Lobby_ZN_1_FLR_2 WSHP Cooling Coil Air Inlet Node,  !- Air Outlet Node Name",
		"    FanPowerCurve, !- Fan Efficiency Ratio Function of Speed Ratio Curve Name",
		"    ,",
		"    WSHP;",

		"  Curve:Exponent,",
		"    FanPowerCurve,      	     !- Name",
		"    0.254542407,              !- Coefficient1 Constant",
		"    0.837259009,              !- Coefficient2 x",
		"    3,                       !- Coefficient3 x**3",
		"    0.458,                 !- Minimum Value of x",
		"    1,                  !- Maximum Value of x",
		"    ,                        !- Minimum Curve Output",
		"    ,                        !- Maximum Curve Output",
		"    Dimensionless,           !- Input Unit Type for X",
		"    Dimensionless;           !- Output Unit Type",

		"  Coil:Heating:Electric,",
		"    Lobby_ZN_1_FLR_2 WSHP Supp Heating Coil,  !- Name",
		"    ALWAYS_ON,    !- Availability Schedule Name",
		"    1.0,                     !- Gas Burner Efficiency",
		"    Autosize,                   !- Nominal Capacity {W}",
		"    Lobby_ZN_1_FLR_2 WSHP SuppHeating Coil Air Inlet Node,  !- Air Inlet Node Name",
		"    Lobby_ZN_1_FLR_2 WSHP Outlet Node;       !- Air Outlet Node Name",

		"  OutdoorAir:Node, PSZ-AC_1:5 OA Node;",
		"  OutdoorAir:Node, Lobby_ZN_1_FLR_2 WSHP OA Node;",

		" Curve:Quadratic, PLF Curve, 0.85, 0.15, 0, 0, 1, 0.0, 1.0, Dimensionless, Dimensionless; ",
		" Curve:Cubic, CubicCurve, 1.0, 0.0, 0.0, 0.0, 0.76, 1.09, , , Dimensionless, Dimensionless; ",
		" Curve:Biquadratic, BiquadraticCurve, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 10, 25.6, 7.2, 48.9, , , Temperature, Temperature, Dimensionless; ",

			});

			ASSERT_FALSE( process_idf( idf_objects ) );
			compare_err_stream( "" );
			OutputProcessor::TimeValue.allocate( 2 );
			DataGlobals::DDOnlySimulation = true;

			ManageSimulation(); // run the design day over the warmup period (24 hrs, 25 days)

			EXPECT_EQ ( VariableSpeedCoils::VarSpeedCoil( 1 ).Name, "LOBBY_ZN_1_FLR_2 WSHP COOLING MODE" );

			EXPECT_EQ ( VariableSpeedCoils::VarSpeedCoil( 2 ).Name, "PSZ-AC_1:5_COOLC STANDARD 4-COMPRESSOR IPAK");

	}
}
