name: Linux Build

on:
  push:
    branches: [ develop ]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ develop ]

jobs:
#  base_build:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-20.04]
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Set up Python 3.7
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.7
#
#    - name: Install System Dependencies
#      shell: bash
#      run: |
#        set -x
#        echo "Using Apt to install dependencies"
#        sudo apt-get update
#        sudo apt-get install libxkbcommon-x11-0 xorg-dev libgl1-mesa-dev
#
#    - name: Create Build Directory
#      run: cmake -E make_directory ./build/
#
#    - name: Configure CMake
#      shell: bash
#      working-directory: ./build/
#      run: cmake -DCMAKE_BUILD_TYPE=Release -DLINK_WITH_PYTHON=ON ..
#
#    - name: Build EnergyPlus
#      working-directory: ./build/
#      shell: bash
#      run: cmake --build . --target energyplus -j 2

  alternate_build_configurations:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Install System Dependencies
        shell: bash
        run: |
          set -x
          echo "Using Apt to install dependencies"
          sudo apt-get update

      - name: Create Build Directory
        run: cmake -E make_directory ./build/

      - name: Configure CMake
        shell: bash
        working-directory: ./build/
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DLINK_WITH_PYTHON=OFF \
                -DUSE_PSYCHROMETRICS_CACHING=OFF \
                -DUSE_GLYCOL_CACHING=OFF \
                -DOPENGL_REQUIRED=OFF \
                -DUSE_PSYCH_STATS=ON \
                -DUSE_PSYCH_ERRORS=OFF \
                -DENABLE_PCH=OFF \
                ../

      - name: Build EnergyPlus
        working-directory: ./build/
        shell: bash
        run: cmake --build . --target energyplus -j 2
